feat: #7 prevent main push

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -5,6 +5,7 @@ echo -e "===\n>> Pre-push Hook: Checking branch name ..."
 BRANCH=`git rev-parse --abbrev-ref HEAD`
 PROTECTED_BRANCHES="^(main|develop)"
 COMMIT_MESSAGE=$(git log -1 --pretty=%B)
+BRANCH_REGEX="(feat|fix)/[0-9]+*"
 
 # echo -e "\n $1 $2 $3 --"
 
@@ -12,6 +13,11 @@ COMMIT_MESSAGE=$(git log -1 --pretty=%B)
 # then
 #   echo -e "\n🚫 You must use (git push origin $BRANCH) (git push origin $BRANCH).\n" && exit 1
 # fi
+
+if [[ "$BRANCH" =~ $PROTECTED_BRANCHES && ! "$COMMIT_MESSAGE" == *.. ]]
+then
+  echo -e "\n🚫 Cannot push to remote $BRANCH branch, please create your own branch and used a PR." && exit 1
+fi
 
 if [[ "$BRANCH" =~ $PROTECTED_BRANCHES && ! "$COMMIT_MESSAGE" == *.. ]]
 then
