feat: update projen, cdk and husky..

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -9,5 +9,11 @@
 
 yarn lint:staged
 
+# Only cdk synth if backend files have been changed.
+if ! git diff --name-only --cached | egrep 'backend' > /dev/null ; then
+  echo "Aborting cdk synth since no backend files have been changed."
+  exit 0
+fi
+
 cd backend
-yarn tsc
+yarn synth
